*** Starting uWSGI 2.0.8 (64bit) on [Mon Dec 29 12:53:49 2014] ***
compiled with version: 4.8.2 on 29 December 2014 10:31:17
os: Linux-3.16.7-x86_64-linode49 #3 SMP Fri Nov 14 16:55:37 EST 2014
nodename: li726-76
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/anx/dota_only/production/doweb
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/anx/dota_only/production/doweb
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 16001
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :9630 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x18d3af0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 727600 bytes (710 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 20, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'doweb.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named doweb.settings
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20666, cores: 1)
spawned uWSGI worker 2 (pid: 20671, cores: 1)
spawned uWSGI worker 3 (pid: 20672, cores: 1)
spawned uWSGI worker 4 (pid: 20673, cores: 1)
spawned uWSGI worker 5 (pid: 20674, cores: 1)
spawned uWSGI worker 6 (pid: 20675, cores: 1)
spawned uWSGI worker 7 (pid: 20676, cores: 1)
spawned uWSGI worker 8 (pid: 20677, cores: 1)
spawned uWSGI worker 9 (pid: 20678, cores: 1)
spawned uWSGI worker 10 (pid: 20679, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 20679|app: -1|req: -1/1] 207.161.75.53 () {44 vars in 768 bytes} [Mon Dec 29 13:14:17 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20666|app: -1|req: -1/2] 207.161.75.53 () {42 vars in 713 bytes} [Mon Dec 29 13:14:20 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.8 (64bit) on [Mon Dec 29 13:26:32 2014] ***
compiled with version: 4.8.2 on 29 December 2014 10:31:17
os: Linux-3.16.7-x86_64-linode49 #3 SMP Fri Nov 14 16:55:37 EST 2014
nodename: li726-76
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/anx/dota_only/production/doweb
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/anx/dota_only/production/doweb
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 16001
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :9630 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x115faa0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 727600 bytes (710 KB) for 10 cores
*** Operational MODE: preforking ***
ImportError: No module named doweb.wsgi
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21184, cores: 1)
spawned uWSGI worker 2 (pid: 21189, cores: 1)
spawned uWSGI worker 3 (pid: 21190, cores: 1)
spawned uWSGI worker 4 (pid: 21191, cores: 1)
spawned uWSGI worker 5 (pid: 21192, cores: 1)
spawned uWSGI worker 6 (pid: 21193, cores: 1)
spawned uWSGI worker 7 (pid: 21194, cores: 1)
spawned uWSGI worker 8 (pid: 21195, cores: 1)
spawned uWSGI worker 9 (pid: 21196, cores: 1)
spawned uWSGI worker 10 (pid: 21197, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 21184|app: -1|req: -1/1] 207.161.75.53 () {42 vars in 713 bytes} [Mon Dec 29 13:26:46 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.8 (64bit) on [Mon Dec 29 13:29:28 2014] ***
compiled with version: 4.8.2 on 29 December 2014 10:31:17
os: Linux-3.16.7-x86_64-linode49 #3 SMP Fri Nov 14 16:55:37 EST 2014
nodename: li726-76
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/anx/dota_only/production/doweb
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 16001
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :9630 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ca9b10
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 727600 bytes (710 KB) for 10 cores
*** Operational MODE: preforking ***
ImportError: No module named doweb.wsgi
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21225, cores: 1)
spawned uWSGI worker 2 (pid: 21230, cores: 1)
spawned uWSGI worker 3 (pid: 21231, cores: 1)
spawned uWSGI worker 4 (pid: 21232, cores: 1)
spawned uWSGI worker 5 (pid: 21233, cores: 1)
spawned uWSGI worker 6 (pid: 21234, cores: 1)
spawned uWSGI worker 7 (pid: 21235, cores: 1)
spawned uWSGI worker 8 (pid: 21236, cores: 1)
spawned uWSGI worker 9 (pid: 21237, cores: 1)
spawned uWSGI worker 10 (pid: 21238, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 21237|app: -1|req: -1/1] 207.161.75.53 () {42 vars in 713 bytes} [Mon Dec 29 13:29:45 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 21238|app: -1|req: -1/2] 207.161.75.53 () {42 vars in 713 bytes} [Mon Dec 29 13:29:47 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
